crestfinewebapp/Models/AnnualReport.cs
namespace crestfinewebapp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class AnnualReport
    {
        public int AnnualReportID { get; set; }

        public DateTime Time { get; set; }

        public decimal? Debt { get; set; }

        public decimal? Amount { get; set; }

        public decimal? AverageAnnualSales { get; set; }
    }
}

crestfinewebapp/Controllers/AnnualReportController.cs
using crestfinewebapp.Models;
using crestfinewebapp.Repositories;
using crestfinewebapp.Repositories.IRepository;
using crestfinewebapp.ViewModels;
using Hangfire;
using Hangfire.Common;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;
using crestfinewebapp.Attributes;

namespace crestfinewebapp.Controllers
{
    [WellbakeAuthorize]
    [CheckOutSession]
    public class AnnualReportController : Controller
    {
        private readonly IDatabaseSelectAccounts<Reports> databaseSelect;
        private readonly IDatabaseSelectReports annualreports;

        public AnnualReportController(IDatabaseSelectReports annualreports)
        {
            this.annualreports = annualreports;

            databaseSelect = new DatabaseSelectAccounts();
            
        }
        // GET: Annual
      
        //Autocheck annual for new Reports
        public async Task<ActionResult> AddReport()
        {
            var manage = new RecurringJobManager();
            manage.AddOrUpdate("annualreports", Job.FromExpression(() => databaseSelect.Selectannualrpts()), Cron.Yearly(1,1));
           
            ViewBag.Error = $"Reports as of {DateTime.Today}";
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSort = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            IEnumerable<AnnualReport> annualReport = await annualreports.GetAnnualReports();
            if (!String.IsNullOrEmpty(searchString))
            {
                annualReport = annualReport.Where(x => x.Time == Convert.ToDateTime(searchString));
            }

            switch (sortOrder)
            {
                case "Date":
                    annualReport = annualReport.OrderBy(s => s.Time);
                    break;
                case "date_desc":
                    annualReport = annualReport.OrderByDescending(s => s.Time);
                    break;
                default:
                    annualReport = annualReport.OrderBy(s => s.Time);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(annualReport.ToPagedList(pageNumber,pageSize));
        }

        public async Task<ActionResult> Details(int id)
        {
            AnnualReport annualReport = await annualreports.GetAnnualReport(id);
            
            return View(annualReport);
        }

        public async Task<FileResult> CreatePDF(int id)
        {
            //trigger the recurring tasks
            MemoryStream workstream = new MemoryStream();
            StringBuilder status = new StringBuilder("");
            DateTime time = DateTime.Today;

            string PDFfileName = string.Format("annualreport" + time.ToString("yyyyMMdd") + "-" + ".pdf");
            Document document = new Document();

            PdfPTable tableLayout = new PdfPTable(3);
            document.SetMargins(0f, 0f, 0f, 0f);
            //create pdf

            //Find the actual report
            AnnualReport annualrpt = await annualreports.GetAnnualReport(id);

            string strAttachment = Server.MapPath("~/Downloads/" + PDFfileName);

            PdfWriter.GetInstance(document, workstream).CloseStream = false;
            document.Open();

            document.Add(await AddContent(tableLayout, annualrpt));
            document.Close();

            byte[] byteInfo = workstream.ToArray();
            await workstream.WriteAsync(byteInfo, 0, byteInfo.Length);
            workstream.Position = 0;

            return File(workstream, "application/pdf", PDFfileName);
        }

        protected async Task<PdfPTable> AddContent(PdfPTable tableLayout, AnnualReport reports)
        {
            float[] headers = { 50, 24, 45};
            //Reports reports = await databaseSelect.Selectannualrpts();
            
            tableLayout.SetWidths(headers);
            tableLayout.WidthPercentage = 100;
            tableLayout.HeaderRows = 1;

            tableLayout.AddCell(new PdfPCell(new Phrase("WellBake Report", new Font(Font.FontFamily.HELVETICA, 8, 1, new iTextSharp.text.BaseColor(0, 0, 0))))
            {
                Colspan = 12,
                Border = 0,
                PaddingBottom = 5,
                HorizontalAlignment = Element.ALIGN_CENTER
            });

            AddCellToHeader(tableLayout, "Credit");
            AddCellToHeader(tableLayout, "Debit");
            AddCellToHeader(tableLayout, "AverageSales");

            //add body
            AddCellToBody(tableLayout, reports.Amount.ToString());
            AddCellToBody(tableLayout, reports.Debt.ToString());
            AddCellToBody(tableLayout, reports.AverageAnnualSales.ToString());


            tableLayout.AddCell(new PdfPCell(new Phrase("Annual Report" + " " + DateTime.Today, new Font(Font.FontFamily.HELVETICA, 8, 1, new iTextSharp.text.BaseColor(0, 0, 0))))
            {
                Colspan = 12,
                Border = 0,
                PaddingBottom = 5,
                HorizontalAlignment = Element.ALIGN_BOTTOM
            });

            return tableLayout;
        }

        private static void AddCellToHeader(PdfPTable tableLayout, string cellText)
        {
            tableLayout.AddCell(new PdfPCell(new Phrase(cellText, new Font(Font.FontFamily.HELVETICA, 8, 1, iTextSharp.text.BaseColor.YELLOW)))
            {
                HorizontalAlignment = Element.ALIGN_LEFT,
                Padding = 5,
                BackgroundColor = new iTextSharp.text.BaseColor(128, 0, 0)
            });
        }

        private static void AddCellToBody(PdfPTable tableLayout, string cellText)
        {
            tableLayout.AddCell(new PdfPCell(new Phrase(cellText, new Font(Font.FontFamily.HELVETICA, 8, 1, iTextSharp.text.BaseColor.BLACK)))
            {
                HorizontalAlignment = Element.ALIGN_LEFT,
                Padding = 5,
                BackgroundColor = new iTextSharp.text.BaseColor(255, 255, 255)
            });
        }
    }
}

crestfinewebapp/Views/AnnualReport/Details.cshtml
@model crestfinewebapp.AnnualReport

@{
    ViewBag.Title = "Annual Report";
}

<h2>Details</h2>

<div>
    <h4>@{
        ViewBag.Time = $"{DateTime.Now}";
    }</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Debt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Debt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AverageAnnualSales)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AverageAnnualSales)
        </dd>

    </dl>
</div>
<p class="col-md-8">
        @Html.ActionLink("PDF", "CreatePDF", new { id = Model.AnnualReportID }, new {@class= "btn btn-info" })
        @Html.ActionLink("Back to List", "Index", new {@class= "btn btn-default" })
    
</p>

crestfinewebapp/Views/AnnualReport/Index.cshtml
@model PagedList.IPagedList<crestfinewebapp.AnnualReport>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Annual Reports";
}

<h2>Annual Reports</h2>

<div class="col-md-2">
    @Html.ActionLink("Refresh", "AddReport", "AnnualReport", new { @class = "btn btn-default" })
</div>

@using (Html.BeginForm())
{
    <div class="form-group">
        Find By Date:@Html.TextBox("SearchDate", ViewBag.CurrentFilter as string)
        <input class="btn btn-primary" type="submit" , value="Search" />
    </div>
}
<table class="table table-hover">
    <tr>
        <th>
            Debt
        </th>
        <th>
            Amount
        </th>
        <th>
            AnnualAverageSales
        </th>
        <th>
            @Html.ActionLink("Time", "Index", new { sortOrder = ViewBag.DateSort })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Debt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AverageAnnualSales)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                    @Html.ActionLink("Details", "Details", new { id = item.AnnualReportID }, new {@class="btn btn-default btn-primary" })
            </td>
            <td>
                    @Html.ActionLink("PDF", "CreatePDF", new { id = item.AnnualReportID }, new {@class="btn btn-success" })
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))