crestfinewebapp/Models/WeekReport.cs
namespace crestfinewebapp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class WeekReport
    {
        [Key]
        public int ReportID { get; set; }
        [Key]
        public DateTime Time { get; set; }
        public decimal? Debt { get; set; }
        public decimal? Amount { get; set; }
        public decimal? AverageWeekSales { get; set; }
    }
}

crestfinewebapp/Controllers/WeekReportController.cs
using crestfinewebapp.Models;
using crestfinewebapp.Repositories;
using crestfinewebapp.Repositories.IRepository;
using crestfinewebapp.ViewModels;
using Hangfire;
using Hangfire.Common;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;
using crestfinewebapp.Attributes;

namespace crestfinewebapp.Controllers
{
    /// <summary>
    /// this returns view for Week Reports
    /// </summary>
    [WellbakeAuthorize]
    [CheckOutSession]
    public class WeekReportController : Controller
    {
        private readonly IDatabaseSelectAccounts<Reports> dbSelect;
        private readonly IDatabaseSelectReports weekreport;

        public WeekReportController(IDatabaseSelectReports weekreport)
        {
            this.weekreport = weekreport;
            dbSelect = new DatabaseSelectAccounts();
        }
        public async Task<ActionResult> AddReport()
        {
            var manage = new RecurringJobManager();
            manage.AddOrUpdate("weekreports", Job.FromExpression(() => dbSelect.Selectweekrpts()), Cron.Weekly(DayOfWeek.Monday,6));

            ViewBag.Error = $"Reports as of {DateTime.Today}";
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSort = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            
            //RecurringJob.Trigger("weekreports");
            IEnumerable<WeekReport> weekReport = await weekreport.GetWeekReports();

            if (!String.IsNullOrEmpty(searchString))
            {
                weekReport = weekReport.Where(x => x.Time == Convert.ToDateTime(searchString));
            }

            switch (sortOrder)
            {
                case "Date":
                    weekReport = weekReport.OrderBy(s => s.Time);
                    break;
                case "date_desc":
                    weekReport = weekReport.OrderByDescending(s => s.Time);
                    break;
                default:
                    weekReport = weekReport.OrderBy(s => s.Time);
                    break;
            }


            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(weekReport.ToPagedList(pageNumber, pageSize));
        }

        public async Task<ActionResult> Details(int id)
        {
            WeekReport weekReport = await weekreport.GetWeekReport(id);
            return View(weekReport);
        }

        public async Task<FileResult> CreatePDF(int id)
        {
            MemoryStream workstream = new MemoryStream();
            StringBuilder status = new StringBuilder("");
            DateTime time = DateTime.Today;

            string PDFfileName = string.Format("weekreport" + time.ToString("yyyyMMdd")+"-" +".pdf");
            Document document = new Document();

            PdfPTable tableLayout = new PdfPTable(3);
            document.SetMargins(0f, 0f, 0f, 0f);
            //create pdf

            WeekReport report = await weekreport.GetWeekReport(id);

            string strAttachment = Server.MapPath("~/Downloads/" + PDFfileName);

            PdfWriter.GetInstance(document, workstream).CloseStream = false;
            document.Open();

            document.Add(await AddContent(tableLayout,report));
            document.Close();

            byte[] byteInfo = workstream.ToArray();
            await workstream.WriteAsync(byteInfo, 0, byteInfo.Length);
            workstream.Position = 0;

            return File(workstream, "application/pdf", PDFfileName);
        }

        protected async Task<PdfPTable> AddContent(PdfPTable tableLayout, WeekReport reports)
        {
            float[] headers = { 50, 24, 45};

            tableLayout.SetWidths(headers);
            tableLayout.WidthPercentage = 100;
            tableLayout.HeaderRows = 1;

            tableLayout.AddCell(new PdfPCell(new Phrase("WellBake Report", new Font(Font.FontFamily.HELVETICA, 8, 1, new iTextSharp.text.BaseColor(0, 0, 0))))
            {
                Colspan = 12,
                Border = 0,
                PaddingBottom = 5,
                HorizontalAlignment = Element.ALIGN_CENTER
            });

            AddCellToHeader(tableLayout, "Credit");
            AddCellToHeader(tableLayout, "Debit");
            AddCellToHeader(tableLayout, "AverageSales");

            //add body
            AddCellToBody(tableLayout, reports.Amount.ToString());
            AddCellToBody(tableLayout, reports.Debt.ToString());
            AddCellToBody(tableLayout, reports.AverageWeekSales.ToString());


            tableLayout.AddCell(new PdfPCell(new Phrase("Week Report"+" "+DateTime.Today, new Font(Font.FontFamily.HELVETICA, 8, 1, new iTextSharp.text.BaseColor(0, 0, 0))))
            {
                Colspan = 12,
                Border = 0,
                PaddingBottom = 5,
                HorizontalAlignment = Element.ALIGN_BOTTOM
            });

            return tableLayout;
        }

        private static void AddCellToHeader(PdfPTable tableLayout, string cellText)
        {
            tableLayout.AddCell(new PdfPCell(new Phrase(cellText, new Font(Font.FontFamily.HELVETICA, 8, 1, iTextSharp.text.BaseColor.YELLOW)))
            {
                HorizontalAlignment = Element.ALIGN_LEFT,
                Padding = 5,
                BackgroundColor = new iTextSharp.text.BaseColor(128, 0, 0)
            });
        }

        private static void AddCellToBody(PdfPTable tableLayout, string cellText)
        {
            tableLayout.AddCell(new PdfPCell(new Phrase(cellText, new Font(Font.FontFamily.HELVETICA, 8, 1, iTextSharp.text.BaseColor.BLACK)))
            {
                HorizontalAlignment = Element.ALIGN_LEFT,
                Padding = 5,
                BackgroundColor = new iTextSharp.text.BaseColor(255, 255, 255)
            });
        }
    }
}

crestfinewebapp/Views/WeekReport/Details.cshtml
@model crestfinewebapp.WeekReport

@{
    ViewBag.Title = "Week Report";
}

<h2>Details</h2>

<div>
    <h4>@{
        ViewBag.Time = $"{DateTime.Now}";
    }</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Debt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Debt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AverageWeekSales)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AverageWeekSales)
        </dd>

    </dl>
</div>
<p class="col-md-8">
        @Html.ActionLink("PDF", "CreatePDF", new { id = Model.ReportID }, new {@class  = "btn btn-info" })

        @Html.ActionLink("Back to List", "Index", new {@class= "btn btn-default" })

</p>

crestfinewebapp/Views/WeekReport/Index.cshtml
@model PagedList.IPagedList<crestfinewebapp.WeekReport>
<!-- IEnumerable<crestfinewebapp.WeekReport>-->
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "Week Reports";
}

<h2>Week Reports</h2>

<div class="col-md-2">
    @Html.ActionLink("Refresh", "AddReport", "WeekReport", new { @class = "btn btn-default" })
</div>

@using (Html.BeginForm())
{
    <div class="form-group">
        Find By Date:@Html.TextBox("SearchDate", ViewBag.CurrentFilter as string)
        <input class="btn btn-primary" type="submit" , value="Search" />
    </div>
}

<table class="table table-hover">
    <tr>
        <th>
            Debt
        </th>
        <th>
            Amount
        </th>
        <th>
            AverageWeekSales
        </th>
        <th>
            @Html.ActionLink("Time", "Index", new { sortOrder = ViewBag.DateSort })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Debt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AverageWeekSales)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.ReportID }, new { @class = "btn btn-default btn-primary" })
            </td>
            <td>
                @Html.ActionLink("PDF", "CreatePDF", new { id = item.ReportID }, new { @class = "btn btn-success" })
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))